name: release-builds

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Switch to Xcode 14.2
      run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
    - name: Build (macos, tests)
      run: swift build --build-tests -v
    - name: Build (ios)
      run: xcodebuild -scheme Site -destination "name=iPhone 14"
