name: release-builds

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: sw_vers
      run: sw_vers
    - name: Switch to Xcode 16.4
      run: sudo xcode-select -s "/Applications/Xcode_16.4.app/Contents/Developer"
    - name: Show SDKs
      run: xcodebuild -showsdks
    - name: Build / Test
      run: swift test -v -Xswiftc -warnings-as-errors
    - name: Build iOS / macOS
      run: xcodebuild -verbose -scheme Site -destination "generic/platform=iOS Simulator" -destination "generic/platform=macOS" -destination "generic/platform=tvOS Simulator"
