name: release-builds

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Switch to Xcode 14.2
      run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
    - name: Build (tests)
      run: swift build --build-tests -v

# Too many failures building with xcodebuild.
#    - name: Build (macos, ios)
#      run: xcodebuild -scheme Site -destination "platform=macOS" -destination "platform=iOS Simulator,name=iPhone 14"
