name: release-builds

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v5
    - name: sw_vers
      run: sw_vers
    - name: Available Xcodes
      run: ls /Applications | grep Xcode
    - name: Switch to Xcode 26 Beta
      run: sudo xcode-select -s "/Applications/Xcode_26.0.app/Contents/Developer"
    - name: Xcode - Accept License
      run: sudo xcodebuild -license accept
    - name: Xcode - First Launch
      run: xcodebuild -runFirstLaunch
    - name: Xcode Version
      run: xcodebuild -version
    - name: Install iOS
      run: xcodebuild -downloadPlatform iOS
    - name: Install tvOS
      run: xcodebuild -downloadPlatform tvOS
    - name: Show SDKs
      run: xcodebuild -showsdks
    - name: Show Destinations
      run: xcodebuild -scheme SiteApp -showdestinations
    - name: Build / Test
      run: xcodebuild test -verbose -skipPackagePluginValidation -scheme SiteApp -destination "platform=iOS Simulator,name=iPhone 16,OS=18.6"
    - name: Build iOS / macOS / tvOS
      run: xcodebuild -verbose -skipPackagePluginValidation -scheme SiteApp -destination "generic/platform=iOS Simulator" -destination "generic/platform=macOS" -destination "generic/platform=tvOS Simulator"
