name: release-builds

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Switch to Xcode 15.2
      run: sudo xcode-select -s "/Applications/Xcode_15.2.app"
    - name: Build / Test
      run: swift build -v
    - name: Build iOS / macOS
      run: xcodebuild -verbose -scheme Site -destination "generic/platform=iOS Simulator" -destination "generic/platform=macOS" -destination "generic/platform=tvOS Simulator"
