name: release-builds

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - name: Switch to Xcode 15.0
      run: sudo xcode-select -s "/Applications/Xcode_15.0.app"
    - name: Build / Test
      run: swift test -v

# Too many failures building with xcodebuild.
#    - name: Build (macos, ios)
#      run: xcodebuild -scheme Site -destination "platform=macOS" -destination "platform=iOS Simulator,name=iPhone 14"
